- CONTRIBUTING.en-US.md
- CONTRIBUTING.md
> docs: 修改注释错误

- docs/docs/.vitepress/utils/sidebar.ts
- docs/docs/components/card.md
- packages/fighting-components/button/src/button.ts
- packages/fighting-components/button/src/button.vue
- packages/fighting-theme/src/button.scss
- packages/fighting-type/link.d.ts
- pnpm-lock.yaml
- start/src/App.vue
> docs: 增加card组件文档&增加圆形按钮

- CONTRIBUTING.en-US.md
- CONTRIBUTING.md
- packages/fighting-theme/config/size.scss
- packages/fighting-theme/config/variables.scss
- packages/fighting-theme/src/button.scss
> refactor: 按钮组件样式代码调整

- CHANGELOG.en-US.md
- CHANGELOG.md
- packages/fighting-test/button.spec.ts
docs: 修改changelog文档, 并更新对应英文version
> docs: 修改changelog文档, 并更新对应英文version 

- packages/fighting-components/aside/index.ts
- packages/fighting-components/aside/src/aside.ts
- packages/fighting-components/aside/src/aside.vue
- packages/fighting-components/button/src/button.vue
- packages/fighting-components/container/index.ts
- packages/fighting-components/container/src/container.vue
- packages/fighting-components/footer/index.ts
- packages/fighting-components/footer/src/footer.ts
- packages/fighting-components/footer/src/footer.vue
- packages/fighting-components/header/index.ts
- packages/fighting-components/header/src/header.ts
- packages/fighting-components/header/src/header.vue
- packages/fighting-components/index.ts
- packages/fighting-components/main/index.ts
- packages/fighting-components/main/src/main.ts
- packages/fighting-components/main/src/main.vue
- packages/fighting-theme/index.scss
- packages/fighting-theme/src/aside.scss
- packages/fighting-theme/src/container.scss
- packages/fighting-theme/src/footer.scss
- packages/fighting-theme/src/header.scss
- packages/fighting-theme/src/main.scss
- start/index.html
- start/src/App.vue
> feat: 新增 FContainer 组件

- .vscode/settings.json
- packages/fighting-components/dialog/index.ts
- packages/fighting-components/dialog/src/dialog.ts
- packages/fighting-components/dialog/src/dialog.vue
- packages/fighting-components/index.ts
- packages/fighting-theme/index.scss
- packages/fighting-theme/src/dialog.scss
- start/src/App.vue
已实现的功能
- title
- visible
- text
- show-close
- modal
- width
- modal-close
- top
> Feat dialog

- packages/fighting-components/list-item/src/list-item.ts
- packages/fighting-components/list-item/src/list-item.vue
- packages/fighting-components/list/src/list.ts
- packages/fighting-components/list/src/list.vue
- packages/fighting-theme/src/list-item.scss
- packages/fighting-theme/src/list.scss
- `f-list` add hoverShow
- `f-list` fix maxHight 
- `f-list-item`  add  maxHight
- `f-list` add split
- `f-list` add showNum and showDisc
> feat(list):update list component

- docs/docs/.vitepress/utils/sidebar.ts
- docs/docs/components/message.md
- packages/fighting-components/index.ts
- packages/fighting-components/message/index.ts
- packages/fighting-components/message/src/instances.ts
- packages/fighting-components/message/src/message.ts
- packages/fighting-components/message/src/message.vue
- packages/fighting-components/message/src/method.ts
- packages/fighting-test/message.spec.ts
- packages/fighting-theme/index.scss
- packages/fighting-theme/src/message.scss
- packages/fighting-utils/index.ts
- packages/fighting-utils/install.ts
- pnpm-lock.yaml
- start/src/App.vue
- 组件功能基本完成
- 文档、测试代码当前编写较少，可后续补充
@Tyh2001  `scss`文件内最后位置动画在这一块的代码感觉可以优化一下，我不太会用`SCSS`
> feat: 新增Message组件

- packages/fighting-components/alert/src/alert.ts
- packages/fighting-components/alert/src/alert.vue
- packages/fighting-components/alert/src/interface.d.ts
> feat: 更新 alter 组件

- .vscode/settings.json
- docs/docs/.vitepress/utils/sidebar.ts
- docs/docs/components/swap.md
- packages/fighting-design/swap/src/interface.d.ts
- packages/fighting-design/swap/src/swap.ts
- packages/fighting-design/swap/src/swap.vue
- packages/fighting-theme/src/swap.scss
> feat(swap): 新增图标切换组件 🌷🌷🌷

- packages/fighting-theme/src/image-preview.scss
更改前：![image](https://user-images.githubusercontent.com/57850101/198192373-a1daaa85-bf40-4712-bf8d-a749205f55d7.png)
更改后：
> refactor: Image Preview组件按钮图标样式更改

- packages/fighting-design/README.md
> docs: 更改错别字

- packages/fighting-design/button/src/button.vue
> fix: 按钮组件样式

- packages/fighting-design/swap/src/swap.vue
> refactor: 还原swap组件emit写法

- docs/docs/components/message.md
- docs/docs/components/notification.md
- docs/docs/components/popup.md
- docs/docs/components/progress.md
- packages/fighting-design/image-preview/src/props.ts
- packages/fighting-design/image/src/props.ts
- packages/fighting-design/link/src/props.ts
- packages/fighting-design/list-item/src/props.ts
- packages/fighting-design/list/src/props.ts
- packages/fighting-design/loading-bar/src/props.ts
- packages/fighting-design/message/src/props.ts
- packages/fighting-design/notification/src/props.ts
- packages/fighting-design/page-header/src/props.ts
- packages/fighting-design/popup/src/props.ts
- packages/fighting-design/progress/src/props.ts
- packages/fighting-design/radio-group/src/props.ts
- packages/fighting-design/radio/src/props.ts
> refactor: 部分props文件添加注释

- docs/docs/components/_demos/checkbox/demo1.vue
- packages/fighting-theme/src/checkbox.scss
> docs: fix checkbox demo

- packages/fighting-design/_hooks/use-button/index.ts
- start/src/App.vue
其实这样写，如果传入的 slot 应该只能是单标签或者文本。因为我们的computed只计算了slot 的 chilren[0]
> fix: slot 改变不会触发响应式

- packages/fighting-theme/src/tooltip.scss
> fix: 修复 tooltip 组件部分情况disabled无效

- packages/fighting-design/option/src/option.vue
> change handelClose to close

- docs/.vitepress/config/sidebar.ts
- docs/components/ellipsis.md
- packages/fighting-design/components.ts
- packages/fighting-design/ellipsis/__test__/ellipsis.spec.ts
- packages/fighting-design/ellipsis/index.ts
- packages/fighting-design/ellipsis/src/ellipsis.vue
- packages/fighting-design/ellipsis/src/interface.ts
- packages/fighting-design/ellipsis/src/props.ts
- packages/fighting-design/global.d.ts
- packages/fighting-theme/index.scss
- packages/fighting-theme/src/ellipsis.scss
- start/src/App.vue
> Ellipsis -新增组件

- docs/components/switch.md
- packages/fighting-design/switch/src/props.ts
- packages/fighting-design/switch/src/switch.vue
> feat: switch 增加 loading状态

- .gitignore
- docs/components/tag.md
- packages/fighting-design/check-tag/__test__/check-tag.spec.ts
- packages/fighting-design/check-tag/index.ts
- packages/fighting-design/check-tag/src/check-tag.vue
- packages/fighting-design/check-tag/src/interface.ts
- packages/fighting-design/check-tag/src/props.ts
- packages/fighting-design/components.ts
- packages/fighting-design/global.d.ts
- packages/fighting-theme/config/var-check-tag.scss
- packages/fighting-theme/index.scss
- packages/fighting-theme/src/check-tag.scss
- start/src/App.vue
增加了 check tag 选中状态，类似radio功能
新增文档
新增测试
> feat:  Check tag 组件
